name: Live server / ngrok (macos M1)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */7 * * *'  # 7h

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: macos-14
    timeout-minutes: 28800 # 8h

    steps:              
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Setup dependencies
        run: |
          brew install ffmpeg ngrok
        
          # Python dependencies
          pip install -r requirements.txt

      - name: Start and expose server
        run: |
            ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
            cd src
            export NONLOCAL=true
            gunicorn -w 1 --threads 100 index:app &
            ngrok http --domain=${{ secrets.NGROK_DOMAIN }} http://localhost:8000 --log=stdout > ngrok.log 2>&1 &
            echo "Server started, ngrok exposure initiated."
            sleep 28800 # 8h
