name: Live server / ngrok

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */7 * * *'  # 7h

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: ubuntu-20.04
    steps:              
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Setup ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo tar xvzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Start and expose server
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

          cd src
          python index.py &
          ngrok http --domain=${{ secrets.NGROK_DOMAIN }} http://localhost:8000 --log=stdout > ngrok.log 2>&1 &
          echo "Server started, ngrok exposure initiated."
          sleep 28800 # 8h
