name: Live server / ngrok

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

  push:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Stop previous server
        uses: styfle/cancel-workflow-action@0.12.1
  
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ffmpeg ngrok
          pip install -r requirements.txt

      - name: Start and expose server
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

          cd src
          python index.py &
          ngrok http --domain=${{ secrets.NGROK_DOMAIN }} http://localhost:8080 --log=stdout > ngrok.log 2>&1 &
          echo "Server started, ngrok exposure initiated."
          sleep 21600 # 6 hours = 6 * 60 * 60 seconds
