name: Live server / localhost.run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # 5h

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 21600 # 6h

    steps:              
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup dependencies
        run: |
          # FFmpeg
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          sudo tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /usr/local/bin --strip-components=2 ffmpeg-master-latest-linux64-gpl/bin
          rm -rf ffmpeg-master-latest-linux64-gpl.tar.xz

          # Python dependencies
          pip install -r requirements.txt

      - name: Start and expose server
        run: |
            cd src
            mkdir tmp
            export NONLOCAL=true
            git config --global user.email "github-actions@users.noreply.github.com"
            git config --global user.name "website.url"
            ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""

            gunicorn -w 1 --threads 100 index:app &
            python actions/localhost.run.py &
            ssh -o StrictHostKeyChecking=no -R 80:127.0.0.1:8000 localhost.run > tmp/localhost.run.log
