name: Live server / ngrok

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */7 * * *'  # 7h

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 28800 # 8h

    steps:              
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup dependencies
        run: |
          # FFmpeg
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          sudo tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /usr/local/bin --strip-components=2 ffmpeg-master-latest-linux64-gpl/bin
          rm -rf ffmpeg-master-latest-linux64-gpl.tar.xz

          # Ngrok
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo tar xzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
          rm -rf ngrok-v3-stable-linux-amd64.tgz

          # Python dependencies
          pip install -r requirements.txt

      - name: Start and expose server
        run: |
            ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
            cd src
            python index.py &
            ngrok http --domain=${{ secrets.NGROK_DOMAIN }} http://localhost:8000 --log=stdout > ngrok.log 2>&1 &
            echo "Server started, ngrok exposure initiated."
            sleep 28800 # 8h
