name: Live server / localhost.run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */7 * * *'  # 7h

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 28800 # 8h

    steps:              
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup dependencies
        run: |
          # FFmpeg
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          sudo tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /usr/local/bin --strip-components=2 ffmpeg-master-latest-linux64-gpl/bin
          rm -rf ffmpeg-master-latest-linux64-gpl.tar.xz

          # Python dependencies
          pip install -r requirements.txt

          # Server
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""

      - name: Start and expose server
        run: |
            cd src
            export NONLOCAL=true
            git config --global user.email "github-actions@users.noreply.github.com"
            git config --global user.name "website.url"

            mkdir tmp
            gunicorn -w 1 --threads 100 index:app &
            ssh -R 80:localhost:8000 localhost.run > tmp/localhost.run.log &
            python ../.github/workflows/localhost.run.py
            echo "Server started, localhost.run exposure initiated."
            sleep 28800 # 8h
