name: Live server / ngrok (windows)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # every 5h

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: windows-latest
    steps:              
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup ngrok & ffmpeg
        uses: crazy-max/ghaction-chocolatey@v3 
        with: 
          args: install ngrok ffmpeg

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Start and expose server
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          cd src
          Start-Process python index.py -NoNewWindow
          ngrok http --domain=${{ secrets.NGROK_DOMAIN }} http://localhost:8000 --log=stdout > ngrok.log 2>&1 &
          Write-Host "Server started, ngrok exposure initiated."
          sleep 21600
